# Generated by Django 3.2.12 on 2023-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_auto_20230204_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodeservico',
            name='prioridade',
            field=models.CharField(choices=[('0', 'Sem prioridade'), ('1', 'Normal'), ('2', 'Urgente'), ('3', 'Muito Urgente')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amostra',
            name='hora_da_coleta',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='unidade_de_medida',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formulariodeamostra',
            name='id_solicitacao_de_serviço',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='lq',
            field=models.CharField(help_text='valor de referência', max_length=10),
        ),
    ]
